In [1]:
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [2]:
import warnings            
warnings.filterwarnings("ignore")

In [4]:
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("d:/statiscalprograming/input"))

['Hospital_Inpatient_Discharges.csv']

In [5]:
data = pd.read_csv('d:/statiscalprograming/input/Hospital_Inpatient_Discharges.csv')

In [6]:
#data includes how many rows and columns
data.shape
print("Our data has {} rows and {} columns".format(data.shape[0],data.shape[1]))
#Features name in data
data.columns

Our data has 2346760 rows and 37 columns

Index(['Health Service Area', 'Hospital County',
       'Operating Certificate Number', 'Facility Id', 'Facility Name',
       'Age Group', 'Zip Code - 3 digits', 'Gender', 'Race', 'Ethnicity',
       'Length of Stay', 'Type of Admission', 'Patient Disposition',
       'Discharge Year', 'CCS Diagnosis Code', 'CCS Diagnosis Description',
       'CCS Procedure Code', 'CCS Procedure Description', 'APR DRG Code',
       'APR DRG Description', 'APR MDC Code', 'APR MDC Description',
       'APR Severity of Illness Code', 'APR Severity of Illness Description',
       'APR Risk of Mortality', 'APR Medical Surgical Description',
       'Payment Typology 1', 'Payment Typology 2', 'Payment Typology 3',
       'Attending Provider License Number',
       'Operating Provider License Number', 'Other Provider License Number',
       'Birth Weight', 'Abortion Edit Indicator',
       'Emergency Department Indicator', 'Total Charges', 'Total Costs'],
      dtype='object')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2346760 entries, 0 to 2346759
Data columns (total 37 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Facility Id                          float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code - 3 digits                  object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCS Diagnosis Code                   int64
 15  CCS Diagnosis Description            object
 16  CCS Procedure Code                   int64
 17  CCS Procedure Description            object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Attending Provider License Number    float64
 30  Operating Provider License Number    float64
 31  Other Provider License Number        float64
 32  Birth Weight                         int64
 33  Abortion Edit Indicator              object
 34  Emergency Department Indicator       object
 35  Total Charges                        object
 36  Total Costs                          object
dtypes: float64(5), int64(7), object(25)
memory usage: 662.5+ MB

In [8]:
data.head(5)

,Health Service Area,Hospital County,Operating Certificate Number,Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,Payment Typology 2,Payment Typology 3,Attending Provider License Number,Operating Provider License Number,Other Provider License Number,Birth Weight,Abortion Edit Indicator,Emergency Department Indicator,Total Charges,Total Costs
0,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,50 to 69,147,F,White,Not Span/Hispanic,...,NaN,NaN,267162.0,NaN,NaN,0,N,Y,$5620.00,$4561.28
1,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,18 to 29,147,F,White,Not Span/Hispanic,...,NaN,NaN,275408.0,NaN,NaN,0,N,Y,$7404.18,$6933.94
2,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,30 to 49,147,M,White,Not Span/Hispanic,...,NaN,NaN,267162.0,NaN,NaN,0,N,Y,$7931.28,$7154.85
3,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,50 to 69,147,F,White,Not Span/Hispanic,...,NaN,NaN,271326.0,NaN,NaN,0,N,Y,$11304.44,$4584.11
4,Western NY,Chautauqua,602001.0,103.0,Woman's Christian Association,50 to 69,147,M,White,Not Span/Hispanic,...,NaN,NaN,243034.0,NaN,NaN,0,N,Y,$8330.50,$4361.74

In [10]:
data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Operating Certificate Number,2343849.0,5.007196e+06,2.259460e+06,101000.0,2951001.0,5907001.0,7002012.0,7004010.0
Facility Id,2343849.0,1.043335e+03,7.134138e+02,1.0,541.0,1099.0,1450.0,9431.0
Discharge Year,2346760.0,2.015000e+03,0.000000e+00,2015.0,2015.0,2015.0,2015.0,2015.0
CCS Diagnosis Code,2346760.0,1.905531e+02,1.596109e+02,1.0,106.0,159.0,218.0,917.0
CCS Procedure Code,2346760.0,1.127790e+02,8.893687e+01,0.0,0.0,132.0,216.0,999.0
APR DRG Code,2346760.0,4.181138e+02,2.413368e+02,1.0,201.0,383.0,640.0,956.0
APR MDC Code,2346760.0,1.042892e+01,5.923686e+00,0.0,5.0,9.0,15.0,25.0
APR Severity of Illness Code,2346760.0,2.010595e+00,8.973762e-01,0.0,1.0,2.0,3.0,4.0
Attending Provider License Number,2343849.0,2.176429e+06,1.201747e+07,615.0,192318.0,229495.0,257913.0,90999999.0
Operating Provider License Number,1733912.0,2.528763e+06,1.290688e+07,71.0,185515.0,223062.0,253416.0,90999999.0
Other Provider License Number,71336.0,1.297207e+07,2.991695e+07,1307.0,183576.0,227145.0,263416.0,90602218.0
Birth Weight,2346760.0,3.264275e+02,1.000147e+03,0.0,0.0,0.0,0.0,9900.0

In [11]:
data.isna().sum()

Health Service Area                       2911
Hospital County                           2911
Operating Certificate Number              2911
Facility Id                               2911
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                       4427
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCS Diagnosis Code                           0
CCS Diagnosis Description                    0
CCS Procedure Code                           0
CCS Procedure Description                    0
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description        112
APR Risk of Mortality                      112
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                      762346
Payment Typology 3                     1645570
Attending Provider License Number         2911
Operating Provider License Number       612848
Other Provider License Number          2275424
Birth Weight                                 0
Abortion Edit Indicator                      0
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
dtype: int64

In [12]:
data.isnull().sum()

Health Service Area                       2911
Hospital County                           2911
Operating Certificate Number              2911
Facility Id                               2911
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                       4427
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCS Diagnosis Code                           0
CCS Diagnosis Description                    0
CCS Procedure Code                           0
CCS Procedure Description                    0
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description        112
APR Risk of Mortality                      112
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                      762346
Payment Typology 3                     1645570
Attending Provider License Number         2911
Operating Provider License Number       612848
Other Provider License Number          2275424
Birth Weight                                 0
Abortion Edit Indicator                      0
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
dtype: int64

In [31]:
data['Length of Stay'] = data['Length of Stay'].apply(lambda x: str(x).split(' ')[0])

data['Length of Stay'] = pd.to_numeric(data['Length of Stay'])

In [34]:
data['Total Costs'] = data['Total Costs'].apply(lambda x: str(x).replace('$',''))
data['Total Costs'] = pd.to_numeric(data['Total Costs'])
data['Total Charges'] = data['Total Charges'].apply(lambda x: str(x).replace('$',''))
data['Total Charges'] = pd.to_numeric(data['Total Charges'])

In [35]:
data.head()

,Health Service Area,Hospital County,Operating Certificate Number,Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,Payment Typology 2,Payment Typology 3,Attending Provider License Number,Operating Provider License Number,Other Provider License Number,Birth Weight,Abortion Edit Indicator,Emergency Department Indicator,Total Charges,Total Costs
0,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,50 to 69,147,F,White,Not Span/Hispanic,...,NaN,NaN,267162.0,NaN,NaN,0,N,Y,5620.00,4561.28
1,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,18 to 29,147,F,White,Not Span/Hispanic,...,NaN,NaN,275408.0,NaN,NaN,0,N,Y,7404.18,6933.94
2,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,30 to 49,147,M,White,Not Span/Hispanic,...,NaN,NaN,267162.0,NaN,NaN,0,N,Y,7931.28,7154.85
3,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,50 to 69,147,F,White,Not Span/Hispanic,...,NaN,NaN,271326.0,NaN,NaN,0,N,Y,11304.44,4584.11
4,Western NY,Chautauqua,602001.0,103.0,Woman's Christian Association,50 to 69,147,M,White,Not Span/Hispanic,...,NaN,NaN,243034.0,NaN,NaN,0,N,Y,8330.50,4361.74

In [36]:
data.tail()

,Health Service Area,Hospital County,Operating Certificate Number,Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,Payment Typology 2,Payment Typology 3,Attending Provider License Number,Operating Provider License Number,Other Provider License Number,Birth Weight,Abortion Edit Indicator,Emergency Department Indicator,Total Charges,Total Costs
2346755,Long Island,Suffolk,5157003.0,943.0,St Catherine of Siena Hospital,70 or Older,117,M,White,Not Span/Hispanic,...,Medicare,Private Health Insurance,201565.0,NaN,NaN,0,N,Y,43494.0,6637.09
2346756,Long Island,Suffolk,5157003.0,943.0,St Catherine of Siena Hospital,50 to 69,117,M,White,Not Span/Hispanic,...,NaN,NaN,251080.0,272191.0,NaN,0,N,Y,16662.0,3236.18
2346757,Long Island,Suffolk,5157003.0,943.0,St Catherine of Siena Hospital,50 to 69,119,M,White,Unknown,...,NaN,NaN,198807.0,NaN,NaN,0,N,N,7142.0,1862.39
2346758,Long Island,Suffolk,5157003.0,943.0,St Catherine of Siena Hospital,70 or Older,117,M,White,Not Span/Hispanic,...,Medicare,Blue Cross/Blue Shield,268633.0,NaN,NaN,0,N,Y,13070.0,2744.13
2346759,Long Island,Suffolk,5157003.0,943.0,St Catherine of Siena Hospital,30 to 49,117,M,White,Spanish/Hispanic,...,NaN,NaN,269959.0,NaN,NaN,0,N,Y,14637.0,2128.89